name: DynamoDB Export Action
description: Action to export data from DynamoDB table to S3 bucket.

branding:
  icon: upload
  color: blue

inputs:
  table:
    description: |-
      The name of the DynamoDB table to export data from.
    required: true
  s3-bucket:
    description: |-
      The name of the Amazon S3 bucket to export the snapshot to.
    required: true

  s3-prefix:
    description: 'S3 prefix to export data to.'
    required: false
  export-format:
    description: |-
      The format for the exported data. Valid values are DYNAMODB_JSON or ION.
      The default value is DYNAMODB_JSON.
    required: false
    default: DYNAMODB_JSON

outputs:
  export-arn:
    description: |-
      The Amazon Resource Name (ARN) of the table export.
  export-id:
    description: |-
      The ID of the table export.
  export-manifest:
    description: |-
      The name of the manifest file for the export task.

runs:
  using: node20
  main: dist/index.js
